controller_list:
  # - name: ""
    # https://github.com/ros-industrial/ur_modern_driver/issues/261
  - name: /vel_based_pos_traj_controller #or /pos_based_pos_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint